"""Added needs_password_update field

Revision ID: fee81ec4e58f
Revises: 94691586f2dc
Create Date: 2023-09-30 18:01:55.255548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee81ec4e58f'
down_revision = '94691586f2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_password_update', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('needs_password_update')

    # ### end Alembic commands ###
